Define new interface ProxyInterface
facile-it/moka pull request #4
Opened 2017-06-14 19:30 UTC by Giuffre

It seems appropriate to pull out a contract for one of the main objects in our domain to enable further implementations.

2017-06-14 20:02 UTC, xzhayon reviewed
I think there are a couple of stale `use` here and there. Given those, and other comments, I absolutely like it!

2017-06-14 20:02 UTC, xzhavilla commented on src/Moka/Proxy/ProxyInterface.php
> + * Class Proxy
Stale comment.

2017-06-14 20:02 UTC, xzhavilla commented on src/Moka/Proxy/Proxy.php
> +    public function stub(array $methodsWithValues): ProxyInterface
I had doubts about this in the past: should a class with a fluent interface return its actual type - to force the concrete implemention from now on - or the interface itself? I'd really like your opinions on this.

2017-06-14 22:11 UTC, xzhayon reviewed
Excellent! Just a note about StubFactoryTest...

2017-06-14 22:11 UTC, xzhavilla commented on tests/Factory/StubFactoryTest.php
> +        $this->expectException(InvalidArgumentException::class);
I would test this in a StubTest class, and rather verify here that fromArray() fails when it receives something different from an array.

2017-06-15 07:21 UTC, Jean85 requested changes

2017-06-15 07:21 UTC, Jean85 commented on src/Moka/Factory/StubFactory.php
> +                throw new InvalidArgumentException();
Maybe you should pass the error as the previous exception?

2017-06-15 07:21 UTC, Jean85 commented on src/Moka/Proxy/Proxy.php
> +    public function stub(array $methodsWithValues): ProxyInterface
You simply do not have that choice, because changing the return will break the interface; it's a PHP limitation.

2017-06-15 07:21 UTC, Jean85 commented on tests/Factory/StubFactoryTest.php
> +class StubFactoryTest extends \PHPUnit_Framework_TestCase
You should use `PHPUnit\Framework\TestCase` to be forward compatible.

2017-06-15 07:21 UTC, Jean85 commented on src/Moka/Proxy/ProxyInterface.php
> +interface ProxyInterface
What's the reason behind this interface? What purpose of replacement or multiple inheritance do you think will be solvable with this?

2017-06-15 07:23 UTC, xzhavilla commented on src/Moka/Proxy/Proxy.php
> +    public function stub(array $methodsWithValues): ProxyInterface
I know, I wouldn't force it in the interface and make an abstract in that case.

2017-06-15 07:52 UTC, Jean85 commented on src/Moka/Stub/StubSet.php
> +                    'The first parameter must be an instance of %s but of type %s given',
"must be an instance of %s, %s given" is more correct.

2017-06-15 08:21 UTC, xzhavilla commented on tests/Factory/StubFactoryTest.php
> +class StubFactoryTest extends \PHPUnit_Framework_TestCase
Not existing (in PHPUnit 5?).

2017-06-15 08:33 UTC, Jean85 commented on tests/Factory/StubFactoryTest.php
> +class StubFactoryTest extends \PHPUnit_Framework_TestCase
It's present since 5.4: https://github.com/sebastianbergmann/phpunit/blob/5.4/src/ForwardCompatibility/TestCase.php

2017-06-15 08:35 UTC, xzhavilla commented on tests/Factory/StubFactoryTest.php
> +class StubFactoryTest extends \PHPUnit_Framework_TestCase
Oops, thanks.

2017-06-15 08:46 UTC, xzhayon approved these changes

2017-06-15 08:46 UTC, xzhayon approved these changes

2017-06-15 08:49 UTC, merged