Refactor mock engine support with strategies
facile-it/moka pull request #6
Opened 2017-06-16 13:29 UTC by xzhavilla

This is currently supporting PHPUnit and Prophecy.

2017-06-16 21:27 UTC, Giuffre requested changes
Ok, this work is impressive. Now we provide three strategies to generate mock objects. If you agree now we should fix de documentation and the test executors to running with all available mocking engines.

2017-06-16 21:38 UTC, xzhavilla commented
Sure! I have to complete the work on stub return values, and we should also think if we want to provide specific traits for each strategy.

2017-06-16 21:51 UTC, Giuffre commented
Please, @xzhavilla review my updates on README.md. I think we should now push the fact that we support multiple generator engines. Do you agree?

2017-06-17 22:09 UTC, Jean85 approved these changes
All good, just 2 minor fixes..

2017-06-17 22:09 UTC, Jean85 commented on README.md
> +Creates (if not existing already) a proxy containing a mock object according to selected strategy for the class identified by `$fqcn` and optionally assigns an `$alias` to it.
To THE selected strategy...

2017-06-17 22:09 UTC, Jean85 commented on tests/Strategy/Prophecy/NoPriorityTokenTest.php
> +namespace Strategy\Prophecy;
Wrong namespace?

2017-06-19 11:06 UTC, Giuffre approved these changes

2017-06-19 11:06 UTC, merged